```{r setup}
#| include: false 
library(tidyverse) 
library(terra)
library(sf)
```

# Precipitation {.unnumbered}

CHIRPS compare with <https://www.mdpi.com/2073-4441/12/5/1244>

```{r tau}
#| message: false
#| warning: false
#| fig-cap: "Caption."
amazonia <- read_sf("results/data/amazonia/") %>% 
  st_union() %>% 
  st_sf()
chirps <- rast("results/data/precipitation/chirps_tau.nc") %>% 
  mask(amazonia) %>% 
  project(amazonia) %>% 
  as.data.frame(xy = T) %>% 
  filter(pval < 0.05) %>% 
  dplyr::select(-pval) %>% 
  rast()
ggplot() +
  tidyterra::geom_spatraster(data = chirps) +
  geom_sf(data = amazonia, fill = NA) +
  theme_bw() +
  scale_fill_gradient2(expression(tau), na.value = NA) 
```

```{r anom}
#| message: false
#| warning: false
#| fig-cap: "Caption."
anom5 <- rast("results/data/precipitation/chirps_anom.nc")[[39:44]] %>% 
  mean() %>% 
  resample(chirps) %>% 
  mask(chirps) %>% 
  mask(amazonia) %>% 
  project(amazonia)
ggplot() +
  tidyterra::geom_spatraster(data = anom5) +
  geom_sf(data = amazonia, fill = NA) +
  theme_bw() +
  scale_fill_gradient2("5 years anomaly", na.value = NA) 
```
