```{r setup}
#| include: false 
library(tidyverse) 
library(terra)
```

# Precipitation {.unnumbered}

CHIRPS

```{r}
rast("results/data/precipitation/chirps_tau.nc") %>% 
  as.data.frame(xy = T) %>% 
  ggplot(aes(x,y)) +
  geom_raster(aes(fill = tau)) +
  geom_point(aes(size = pval < 0.05)) +
  theme_bw() +
  scale_fill_gradient2(expression(tau)) +
  scale_size_manual(values = c(NA, .1), guide = "none")
```

```{r}
# deforest <- rast("results/data/forest/deforestation_year.tif") %>% 
#   resample(rast(tau)) %>% 
#   as.data.frame(xy = T)
# deforest$tau <- terra::extract(rast(tau), deforest[c("x", "y")])$tau
# deforest %>% 
#   mutate(age = 2022-year) %>% 
#   ggplot(aes(age, tau)) +
#   geom_point() +
#   theme_bw() +
#   geom_smooth()
```

```{r chirps}
#| message: false
#| warning: false
#| eval: false
rast("results/data/precipitation/chirps.nc") %>% 
  as.data.frame(xy = TRUE) %>% 
  gather(index, pr, -x, -y) %>% 
  mutate(index = as.numeric(gsub("pr_", "", index))) %>% 
  mutate(date = time(rast("results/data/precipitation/chirps.nc"))[index]) %>% 
  ggplot(aes(date, pr)) +
  geom_line(aes(group = paste(x,y)), col = "lightgrey", alpha = 0.1) +
  geom_smooth(se = FALSE) +
  theme_bw()
```

```{r}
#| message: false
#| warning: false
#| eval: false
rast("results/data/precipitation/chirps.nc") %>% 
  as.data.frame(xy = TRUE) %>% 
  gather(index, pr, -x, -y) %>% 
  mutate(index = as.numeric(gsub("pr_", "", index))) %>% 
  mutate(date = time(rast("results/data/precipitation/chirps.nc"))[index]) %>% 
  filter(month(date) == 1) %>% 
  group_by(x, y, year = year(date)) %>% 
  summarise(pr = sum(pr)) %>% 
  ggplot(aes(year, pr)) +
  geom_point(aes(group = paste(x,y)), col = "lightgrey", alpha = 0.1) +
  geom_smooth(se = FALSE, method = "lm") +
  theme_bw()
```

```{r}
#| message: false
#| warning: false
#| eval: false
rast("results/data/precipitation/chirps.nc") %>% 
  as.data.frame(xy = TRUE) %>% 
  gather(index, pr, -x, -y) %>% 
  mutate(index = as.numeric(gsub("pr_", "", index))) %>% 
  mutate(date = time(rast("results/data/precipitation/chirps.nc"))[index]) %>% 
  filter(month(date) == 1) %>% 
  group_by(x, y, year = year(date)) %>% 
  summarise(pr = sum(pr)) %>% 
  ungroup() %>% 
  nest(pr, year) %>% 
  mutate(models = map(data, ~broom::tidy(lm(pr ~ year, data = .)))) %>% 
  select(-data) %>% 
  unnest() %>% 
  filter(term == "year") %>% 
  ggplot(aes(x, y, fill = estimate)) +
  geom_raster() +
  theme_bw() +
  scale_fill_viridis_c()
```

```{r}
#| message: false
#| warning: false
#| eval: false
rast("results/data/forest/tmf.nc")[["tmf_year=2022"]] %>% 
  as.data.frame(xy = TRUE) %>% 
    mutate(type = recode(`tmf_year=2022`, 
                       "1" = "undisturbed",
                       "2" = "degraded",
                       "3" = "deforested",
                       "4" = "regrowth",
                       "5" = "water",
                       "6" = "other")) %>% 
  ggplot(aes(y, x, fill = type)) +
  geom_raster() +
  theme_bw() +
  scale_fill_viridis_d()
```
