project:
  type: book
  output-dir: docs

book:
  title: "climfor"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
  appendices:
    - literature.qmd
    - meetings.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1
    number-sections: false

editor: visual
