project:
  type: book
  output-dir: docs

book:
  title: "climfor"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
    - 01_precipitation.qmd
    - 02_temperature.qmd
    - 03_forest.qmd
  appendices:
    - literature.qmd
    - meetings.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1
    number-sections: false

editor: visual
